"""The audit layer: cross-engine correlation, and later validation, as opinion.

review/summary.json is evidence and never merges a finding.  This module
derives a second, explicitly non-authoritative artifact from it: candidates
that group static and LLM findings which name the same defect, each pointing
back at its member fingerprints.  Nothing here alters or removes a review
row, nothing here reaches the exit code, and a FALSE_POSITIVE verdict (when
the validator adds one) is a label on a candidate, never a deletion.

The correlator is deterministic and zero-model, which is why it runs inside
``analyze`` and is regenerated by ``recover-report``; the validator calls a
model and lives behind the separate ``assess`` command.
"""
from __future__ import annotations

import json
import re
from collections import Counter
from pathlib import Path
from typing import Any

from .persist import write_json
from .review import (
    _CATEGORY_ALIASES,
    _CWE_CATEGORIES,
    _LLM_KEYWORD_CATEGORIES,
    _line_number,
    _producer_rank,
    group_nearby,
)
from .tools import TOOL_NAMES

ASSESSMENT_SCHEMA_VERSION = 1
AUTHORITY = "non-authoritative-derived-opinion"
ASSESSMENT_PATH = ("audit", "assessment.json")
VERDICT_LABELS: tuple[str, ...] = ("CONFIRMED", "LIKELY", "UNCERTAIN", "FALSE_POSITIVE")
ORIGINS: tuple[str, ...] = ("static-only", "llm-only", "both")
VALIDATOR = "llm-validator"

NOTICE = (
    "Candidates are model-assisted opinion derived from review/summary.json. They never "
    "alter or remove an evidence row, never affect the exit code, and a FALSE_POSITIVE "
    "verdict is a label, not a deletion."
)

# The static rule set the review layer freezes for its own overlap groups
# (review.py _finding_category, the CWE sets inlined there at 4dbb5c0).
_FROZEN_STATIC_CWES: tuple[tuple[str, frozenset[int]], ...] = (
    ("null-dereference", frozenset({476})),
    ("buffer", frozenset({119, 120, 121, 122, 124, 125, 126, 127, 131, 680, 787, 788, 805})),
    ("uninitialized", frozenset({457})),
    ("resource-leak", frozenset({401, 404, 772, 775})),
    ("format", frozenset({134})),
    ("randomness", frozenset({327, 330, 338})),
)

# A candidate id names the family a reader would triage it under.
_ID_PREFIXES: dict[str, str] = {
    "buffer": "MEM", "null-dereference": "MEM", "uninitialized": "MEM", "lifetime": "MEM",
    "integer-overflow": "MEM", "stack-usage": "MEM", "undefined-behavior": "UB",
    "resource-leak": "RES", "format": "SEC", "randomness": "SEC", "input-validation": "SEC",
    "protocol-parsing": "SEC", "info-leak": "SEC", "hardcoded-secret": "SEC",
    "authentication": "SEC", "trust-boundary": "SEC", "crypto-misuse": "SEC",
    "firmware-update": "SEC", "debug-backdoor": "SEC", "race": "FW", "isr-safety": "FW",
    "volatile-misuse": "FW", "atomicity": "FW", "rtos-sync": "FW", "watchdog": "FW",
    "mmio": "FW", "dma": "FW", "timeout": "FW", "reset-behavior": "FW",
}


def correlation_category(item: dict[str, Any]) -> str:
    """The category a finding correlates under, the same way for both engines.

    The review layer classifies static rows by six frozen rules so that static
    overlap group ids never move; here the full vocabulary applies to both
    engines, and CWE numbers are consulted BEFORE keyword rules.  Otherwise a
    flawfinder CWE-190 whose message says "integer overflow" lands in "buffer"
    via the static keyword table and never meets an LLM "integer-overflow".
    """
    if item.get("engine") == "llm":
        declared = str(item.get("category", "")).strip().lower()
        if declared:
            return _CATEGORY_ALIASES.get(declared, declared)
    value = f"{item.get('cwe', '')} {item.get('rule_id', '')} {item.get('message', '')}"
    match = re.search(r"CWE-?(\d+)", value, re.I)
    cwe = int(match.group(1)) if match else None
    if cwe is not None:
        for category, numbers in (*_FROZEN_STATIC_CWES, *_CWE_CATEGORIES):
            if cwe in numbers:
                return category
    for category, pattern in _LLM_KEYWORD_CATEGORIES:
        if re.search(pattern, value, re.I):
            return category
    return f"CWE-{cwe}" if cwe is not None else "unknown"


def build_assessment(review: dict[str, Any]) -> dict[str, Any]:
    """Correlate a review's findings across engines into candidates.

    Every located finding joins exactly one candidate; findings without a
    usable line cannot be placed and are counted instead of dropped.  The
    result carries no verdicts: those are the validator's to add.
    """
    findings = [item for item in review.get("findings", []) if isinstance(item, dict)]

    def key(item: dict[str, Any]) -> tuple[str, str] | None:
        return (str(item.get("canonical_path", "")), correlation_category(item))

    clusters = group_nearby(findings, key_fn=key)
    candidates: list[dict[str, Any]] = []
    counters: Counter[str] = Counter()
    for (path, category), items in clusters:
        prefix = _ID_PREFIXES.get(category, "GEN")
        counters[prefix] += 1
        candidates.append(_candidate(f"{prefix}-{counters[prefix]:03d}", path, category, items))

    located = {item["fingerprint"] for _key, items in clusters for item in items}
    uncorrelated: Counter[str] = Counter(
        item.get("engine", "static") for item in findings if item.get("fingerprint") not in located
    )
    return {
        "assessment_schema_version": ASSESSMENT_SCHEMA_VERSION,
        "authority": AUTHORITY,
        "notice": NOTICE,
        "review_schema_version": review.get("review_schema_version"),
        "run": {"id": (review.get("run") or {}).get("id")},
        "candidates": candidates,
        "metrics": _metrics(
            candidates,
            uncorrelated={"static": uncorrelated.get("static", 0), "llm": uncorrelated.get("llm", 0)},
            unscheduled=len(candidates),
        ),
    }


def apply_verdicts(
    assessment: dict[str, Any], verdicts: dict[str, dict[str, Any]], unscheduled: int
) -> dict[str, Any]:
    """Attach the validator's verdicts and recompute every metric.

    ``verdicts`` maps a candidate id to the verdict block to file under it
    (label, confidence, decisive line, rationale, provenance); ``unscheduled``
    is how many candidates the validator never dispatched.  Candidates are
    never removed and a candidate with no new verdict keeps whatever it had,
    so a second ``assess`` extends the first rather than replacing it.
    """
    candidates = []
    for candidate in assessment.get("candidates", []):
        verdict = verdicts.get(candidate["id"])
        if verdict is None:
            candidates.append(candidate)
            continue
        detected_by = dict(candidate.get("detected_by") or {})
        validators = [name for name in detected_by.get("validators", []) if name != VALIDATOR]
        detected_by["validators"] = [*validators, VALIDATOR]
        candidates.append({**candidate, "verdict": dict(verdict), "detected_by": detected_by})
    previous = dict(assessment.get("metrics", {}))
    return {
        **assessment,
        "candidates": candidates,
        "metrics": _metrics(
            candidates, uncorrelated=dict(previous.get("uncorrelated", {})), unscheduled=int(unscheduled),
        ),
    }


def carry_verdicts(fresh: dict[str, Any], previous: dict[str, Any] | None) -> dict[str, Any]:
    """Re-attach the verdicts of an earlier assessment to a regenerated one.

    ``recover-report`` rebuilds the correlation from the review, which is
    deterministic and cheap; the verdicts were bought with model time and
    must survive that rebuild.  Candidates are matched on ``key``, which is
    stable across runs, never on the ordinal id.
    """
    if not isinstance(previous, dict):
        return fresh
    by_key = {
        candidate.get("key"): candidate["verdict"]
        for candidate in previous.get("candidates", [])
        if isinstance(candidate, dict) and isinstance(candidate.get("verdict"), dict)
    }
    verdicts = {
        candidate["id"]: by_key[candidate["key"]]
        for candidate in fresh.get("candidates", [])
        if candidate.get("key") in by_key
    }
    if not verdicts:
        return fresh
    unscheduled = int((previous.get("metrics") or {}).get("validation_unscheduled", 0))
    return apply_verdicts(fresh, verdicts, unscheduled)


def _metrics(
    candidates: list[dict[str, Any]], *, uncorrelated: dict[str, int], unscheduled: int
) -> dict[str, Any]:
    by_origin = Counter(candidate["origin"] for candidate in candidates)
    labelled = [
        (candidate["origin"], candidate["verdict"]["label"])
        for candidate in candidates
        if isinstance(candidate.get("verdict"), dict)
    ]
    by_verdict = Counter(label for _origin, label in labelled)
    by_origin_verdict = Counter(labelled)
    validated = len(labelled)
    total = len(candidates)
    if validated:
        caveat_ids = ["validator_ran", "validator_sees_static", "grouping_not_identity"]
        first = (
            f"A validator has run: {validated} of {total} candidates carry a verdict and "
            f"{total - validated} do not ({unscheduled} were never scheduled, by the "
            f"validation_max_candidates cap or the token budget). The validator saw the "
            f"static findings for the same file."
        )
    else:
        caveat_ids = ["no_validator", "validator_sees_static", "grouping_not_identity"]
        first = (
            "No validator has run: every verdict count is zero and unvalidated equals "
            "candidates_total. Run `code-analyzer assess` to add verdicts."
        )
    return {
        "candidates_total": total,
        "by_origin": {origin: by_origin.get(origin, 0) for origin in ORIGINS},
        "by_verdict": {label: by_verdict.get(label, 0) for label in VERDICT_LABELS},
        "by_origin_verdict": {
            origin: {label: by_origin_verdict.get((origin, label), 0) for label in VERDICT_LABELS}
            for origin in ORIGINS
        },
        "llm_only_confirmed": by_origin_verdict.get(("llm-only", "CONFIRMED"), 0),
        "llm_only_confirmed_or_likely": (
            by_origin_verdict.get(("llm-only", "CONFIRMED"), 0)
            + by_origin_verdict.get(("llm-only", "LIKELY"), 0)
        ),
        "static_only_false_positive": by_origin_verdict.get(("static-only", "FALSE_POSITIVE"), 0),
        "validated": validated,
        "unvalidated": total - validated,
        "validation_unscheduled": unscheduled,
        "uncorrelated": {"static": int(uncorrelated.get("static", 0)), "llm": int(uncorrelated.get("llm", 0))},
        # Ids let a viewer localise the sentences; the English text is the
        # machine-readable record and what a non-localising reader sees.
        "caveat_ids": caveat_ids,
        "caveats": [
            first,
            "llm_only_confirmed is produced by a validator that sees the static findings "
            "for the same file; read it as corroborated by a second role, not as an "
            "independent confirmation.",
            "A candidate groups findings that name the same lines and category; it does "
            "not assert that they describe the same defect.",
        ],
    }


def write_assessment(run_dir: Path, assessment: dict[str, Any]) -> Path:
    path = Path(run_dir).joinpath(*ASSESSMENT_PATH)
    path.parent.mkdir(parents=True, exist_ok=True)
    write_json(path, assessment)
    return path


def load_assessment(run_dir: Path) -> dict[str, Any] | None:
    """The assessment beside a run, or ``None`` when absent or unreadable.

    Opinion is optional: a dashboard must render without it, so a missing or
    corrupt file is not an error here.
    """
    path = Path(run_dir).joinpath(*ASSESSMENT_PATH)
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        return None
    if not isinstance(document, dict) or document.get("assessment_schema_version") != ASSESSMENT_SCHEMA_VERSION:
        return None
    if not isinstance(document.get("candidates"), list) or not isinstance(document.get("metrics"), dict):
        return None
    return document


def assessment_summary(assessment: dict[str, Any]) -> dict[str, Any]:
    """The slice of an assessment the manifest carries."""
    metrics = assessment.get("metrics", {})
    return {
        "status": "completed",
        "schema_version": assessment.get("assessment_schema_version"),
        "path": "/".join(ASSESSMENT_PATH),
        "candidates": metrics.get("candidates_total", 0),
        "by_origin": dict(metrics.get("by_origin", {})),
        "validated": metrics.get("validated", 0),
    }


def _candidate(identifier: str, path: str, category: str, items: list[dict[str, Any]]) -> dict[str, Any]:
    producers = sorted({str(item.get("producer") or item["tool"]) for item in items}, key=_producer_rank)
    static_tools = [name for name in producers if name in TOOL_NAMES]
    llm_scanners = [name for name in producers if name not in TOOL_NAMES]
    origin = "both" if static_tools and llm_scanners else ("static-only" if static_tools else "llm-only")
    start = min(_line_number(item["line"]) for item in items)
    end = max(_line_number(item["line"]) for item in items)
    ranked = max(items, key=lambda item: int(item.get("rank", 0)))
    return {
        "id": identifier,
        # Stable across runs, unlike the ordinal id: the same defect at the
        # same lines keys the same way whatever else changed in the review.
        "key": f"{path}:{category}:{start}-{end}",
        "canonical_path": path,
        "line_start": start,
        "line_end": end,
        "category": category,
        "origin": origin,
        "sources": producers,
        "engines": sorted({str(item.get("engine", "static")) for item in items}),
        "member_fingerprints": [item["fingerprint"] for item in items],
        "severity": ranked.get("severity", "unknown"),
        "detected_by": {"static_tools": static_tools, "llm_scanners": llm_scanners, "validators": []},
        "verdict": None,
    }
