from __future__ import annotations

import json
from typing import Any

from .grading import grading_reference


def _json_for_html(value: dict[str, Any]) -> str:
    payload = json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    return (
        payload.replace("&", "\\u0026").replace("<", "\\u003c").replace(">", "\\u003e")
        .replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    )


def render(manifest: dict[str, Any], review: dict[str, Any] | None = None) -> str:
    data = dict(review or {
        "review_schema_version": 2, "findings": [], "diagnostics": [],
        "tools": manifest.get("tools", {}),
        "source_manifest": {"total_files": manifest.get("source_inventory", {}).get("total", 0), "files": []},
        "overlap_groups": [], "total_findings": 0, "total_diagnostics": 0,
        "finding_counts": {"total": 0, "build-aware": 0, "source-only": 0},
        "grading_reference": grading_reference(),
        "review_level_counts": {}, "review_level_counts_by_context": {"build-aware": {}, "source-only": {}},
        "report_integrity": {"status": "complete", "omitted_units": []}, "coverage_gaps": [],
    })
    data["execution_manifest"] = manifest
    return _TEMPLATE.replace("__CODE_ANALYZER_DATA__", _json_for_html(data))


_TEMPLATE = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="light dark"><title>Code Analyzer Dashboard</title>
<style>
:root{color-scheme:light;--bg:#f2f5fa;--surface:#fff;--soft:#f8fafc;--ink:#162136;--muted:#607086;--line:#d7dfeb;--brand:#3153d5;--critical:#8c1d40;--high:#c33b2e;--medium:#a86100;--low:#2774a6;--info:#557083;--unknown:#687180;--error:#b42318;--warning:#a86100;--style:#2774a6;--information:#557083;--unmapped:#687180;--ok:#16734a;--warn:#a45b00;--bad:#b42318}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif}a{color:var(--brand)}button,input,select{font:inherit;border:1px solid var(--line);border-radius:.5rem;background:var(--surface);color:var(--ink);padding:.5rem .65rem}button{cursor:pointer}.hero{background:#15264b;color:#fff;padding:1.5rem max(1rem,calc((100% - 1400px)/2))}.hero h1{margin:.15rem 0}.hero p{margin:.25rem 0;color:#dce5ff}.hero a{color:#fff}.meta{display:flex;gap:1rem;flex-wrap:wrap}.nav{position:sticky;top:0;z-index:2;display:flex;gap:1rem;overflow:auto;padding:.65rem max(1rem,calc((100% - 1400px)/2));background:var(--surface);border-bottom:1px solid var(--line)}main{width:min(1400px,calc(100% - 2rem));margin:auto;padding:1rem 0 3rem}section{scroll-margin-top:4rem;margin:1.4rem 0}.section-head{display:flex;justify-content:space-between;align-items:center}.muted{color:var(--muted)}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(10rem,1fr));gap:.75rem}.card,.panel,.tool-card{background:var(--surface);border:1px solid var(--line);border-radius:.75rem;padding:1rem;box-shadow:0 8px 24px rgba(30,48,80,.06)}.card strong{display:block;font-size:1.7rem}.charts,.tools{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem}.bar{display:grid;grid-template-columns:minmax(5rem,35%) 1fr auto;gap:.5rem;align-items:center;margin:.45rem 0}.track{height:.6rem;background:#e7ebf2;border-radius:1rem;overflow:hidden}.fill{display:block;height:100%;background:var(--brand)}.tool-card h3{display:inline}.badge{display:inline-block;border-radius:1rem;padding:.16rem .5rem;background:#e8edf7;margin-left:.45rem}.tool-values{display:grid;grid-template-columns:auto 1fr;gap:.2rem .75rem}.tool-values dt{color:var(--muted)}.tool-values dd{margin:0}.links{display:flex;gap:.7rem;flex-wrap:wrap}.table-wrap{overflow:auto;background:var(--surface);border:1px solid var(--line);border-radius:.75rem}table{border-collapse:collapse;width:100%}th,td{padding:.6rem;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{background:var(--soft);position:sticky;top:0}.controls{display:grid;grid-template-columns:2fr repeat(6,1fr) auto;gap:.6rem;margin-bottom:.7rem}.control{display:grid;gap:.2rem}.pagination{display:flex;justify-content:space-between;align-items:center;margin-top:.7rem}.severity-critical{color:var(--critical)}.severity-high{color:var(--high)}.severity-medium{color:var(--medium)}.severity-low{color:var(--low)}.severity-info{color:var(--info)}.severity-unknown{color:var(--unknown)}.review-error{color:var(--error)}.review-warning{color:var(--warning)}.review-style{color:var(--style)}.review-information{color:var(--information)}.review-unmapped{color:var(--unmapped)}.location{white-space:nowrap}.file-list{max-height:18rem;overflow:auto}.notice{border-left:4px solid var(--warn);padding:.7rem 1rem;background:#fff5df}.empty{text-align:center;color:var(--muted)}
@media(max-width:900px){.cards{grid-template-columns:repeat(2,1fr)}.charts,.tools{grid-template-columns:1fr}.controls{grid-template-columns:1fr 1fr}}@media(max-width:560px){.cards,.controls{grid-template-columns:1fr}.section-head{display:block}}
@media(prefers-color-scheme:dark){:root{color-scheme:dark;--bg:#101827;--surface:#182234;--soft:#202c40;--ink:#edf2fa;--muted:#aab6c8;--line:#344157}.track{background:#344157}.notice{background:#352b18}}
@media print{.nav,.controls,.pagination,button{display:none!important}body{background:#fff}.card,.panel,.tool-card{box-shadow:none}}
</style></head><body>
<header class="hero"><h1>Code Analyzer Dashboard</h1><p id="project">Loading report…</p><div class="meta" id="run-meta"></div><a href="review/summary.json">Open review JSON</a></header>
<nav class="nav"><a href="#overview">Overview</a><a href="#grading">Grading reference</a><a href="#distribution">Distribution</a><a href="#tools">Tools</a><a href="#scope">Scope</a><a href="#overlap">Overlap</a><a href="#diagnostics">Diagnostics</a><a href="#findings">Findings</a></nav>
<main><p class="notice">Derived findings are non-authoritative. Confirm every item against its linked native artifact and the analyzed build configuration.</p>
<section id="overview"><div class="section-head"><h2>Overview</h2><span class="muted" id="overall-status"></span></div><div id="integrity-warning"></div><div class="cards" id="cards"></div></section>
<section id="grading"><div class="section-head"><h2>Code review grading reference</h2><span class="muted" id="grading-section"></span></div><article class="panel"><dl class="tool-values" id="grading-values"></dl><div class="tools" id="grading-levels"></div><p class="notice" id="grading-note"></p></article></section>
<section id="distribution"><div class="section-head"><h2>Finding distribution</h2><span class="muted">Reference levels and evidence contexts are shown separately</span></div><div class="charts"><article class="panel"><h3>Build-aware review level</h3><div id="severity-build"></div></article><article class="panel"><h3>Source-only review level</h3><div id="severity-source"></div></article><article class="panel"><h3>Build-aware by analyzer</h3><div id="tool-build"></div></article><article class="panel"><h3>Source-only by analyzer</h3><div id="tool-source"></div></article><article class="panel"><h3>Top CWE (all)</h3><div id="cwe-chart"></div></article><article class="panel"><h3>Top files (all)</h3><div id="file-chart"></div></article></div></section>
<section id="tools"><div class="section-head"><h2>Execution and native evidence</h2><span class="muted">Statuses, coverage, units, and artifacts</span></div><div class="tools" id="tool-cards"></div></section>
<section id="scope"><div class="section-head"><h2>Scan scope</h2></div><article class="panel"><dl class="tool-values" id="scope-values"></dl><details><summary id="source-summary">Source files</summary><ol class="file-list" id="source-files"></ol></details></article></section>
<section id="overlap"><div class="section-head"><h2>Cross-tool nearby overlap</h2><span class="muted" id="overlap-count"></span></div><div class="table-wrap"><table><thead><tr><th>Category</th><th>Location</th><th>Tools</th><th>Evidence</th><th>Action</th></tr></thead><tbody id="overlap-body"></tbody></table></div></section>
<section id="diagnostics"><div class="section-head"><h2>Tool diagnostics</h2><span class="muted" id="diagnostic-count"></span></div><div class="table-wrap"><table><thead><tr><th>Severity</th><th>Tool</th><th>Category</th><th>Fatal</th><th>Location</th><th>Message</th><th>Evidence</th></tr></thead><tbody id="diagnostic-body"></tbody></table></div></section>
<section id="findings"><div class="section-head"><h2>Findings</h2><span class="muted" id="finding-total"></span></div><p class="notice" id="context-notice" hidden></p><div class="controls"><label class="control">Search<input id="search" type="search" placeholder="Rule, CWE, file, or message"></label><label class="control">Context<select id="context"><option value="">All contexts</option><option value="build-aware">Build-aware</option><option value="source-only">Source-only</option></select></label><label class="control">Review level<select id="review-level"><option value="">All review levels</option></select></label><label class="control">Normalized severity<select id="severity"><option value="">All severities</option></select></label><label class="control">Analyzer<select id="tool"><option value="">All analyzers</option></select></label><label class="control">CWE<select id="cwe"><option value="">All CWE</option></select></label><label class="control">Sort<select id="sort"><option value="priority">Priority</option><option value="location">Location</option><option value="tool">Analyzer</option><option value="rule">Rule</option></select></label><button id="reset" type="button">Reset</button></div><div class="table-wrap"><table><thead><tr><th>Review level</th><th>Normalized severity</th><th>Context</th><th>Analyzer</th><th>Rule</th><th>CWE</th><th>Location</th><th>Message</th><th>Evidence</th></tr></thead><tbody id="finding-body"></tbody></table></div><div class="pagination"><span id="page-status" class="muted"></span><span><select id="page-size"><option>25</option><option selected>50</option><option>100</option><option>250</option></select> <button id="previous">Previous</button> <button id="next">Next</button></span></div></section>
</main><noscript><p>JavaScript is required. The complete data remains in <a href="review/summary.json">review/summary.json</a>.</p></noscript>
<script>
"use strict";(()=>{const state={ready:false,timer:null},show=message=>{if(state.ready)return;state.ready=true;if(state.timer!==null)window.clearTimeout(state.timer);const project=document.getElementById("project");if(project)project.textContent="Dashboard unavailable";const main=document.querySelector("main"),notice=document.createElement("p");notice.id="dashboard-error";notice.className="notice";notice.append(document.createTextNode(`${message} Open `));[["manifest.json","manifest.json"],["review/summary.json","review/summary.json"]].forEach(([label,path],index)=>{if(index)notice.append(document.createTextNode(" or "));const link=document.createElement("a");link.href=path;link.textContent=label;notice.append(link)});notice.append(document.createTextNode(" to inspect the report data."));if(main)main.prepend(notice)};window.__codeAnalyzerDashboard={ready:()=>{state.ready=true;if(state.timer!==null)window.clearTimeout(state.timer)},fail:show};window.addEventListener("error",event=>show(`Dashboard initialization failed: ${event.message||"unknown script error"}.`));window.addEventListener("unhandledrejection",()=>show("Dashboard initialization failed with an unhandled error."));state.timer=window.setTimeout(()=>show("Dashboard initialization did not complete."),1000)})();
</script><script id="report-data" type="application/json">__CODE_ANALYZER_DATA__</script><script>
"use strict";(()=>{const review=JSON.parse(document.getElementById("report-data").textContent),manifest=review.execution_manifest||{};const id=x=>document.getElementById(x),make=(tag,cls,value)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(value!==undefined&&value!==null)n.textContent=String(value);return n},number=x=>new Intl.NumberFormat().format(Number(x||0));
const safeHref=path=>{if(typeof path!=="string"||!path||path.startsWith("/")||path.includes("\\")||path.includes(":"))return null;const parts=path.split("/");if(parts.some(p=>!p||p==="."||p===".."||!/^[A-Za-z0-9._-]+$/.test(p)))return null;return parts.map(encodeURIComponent).join("/")},link=(label,path)=>{const href=safeHref(path);if(!href)return make("span","muted","—");const a=make("a","",label);a.href=href;return a},location=x=>`${x.canonical_path||x.file||"<unknown>"}${x.line?":"+x.line:""}${x.column?":"+x.column:""}`;
id("project").textContent=review.project||manifest.source||"Unknown source";document.title=`${String(review.project||"Code Analyzer").split(/[\\/]/).filter(Boolean).pop()||"Code Analyzer"} · Code Analyzer`;[["Run",manifest.run_id],["Analyzer",manifest.analyzer_version],["Context",manifest.analysis_context],["Finished",manifest.finished_at]].forEach(([k,v])=>{const n=make("span");n.append(make("strong","",`${k}: `),document.createTextNode(v||"—"));id("run-meta").append(n)});id("overall-status").textContent=`${manifest.status||"unknown"} · exit ${manifest.exit_code??"—"}`;
const grading=review.grading_reference||{},gradingDocument=grading.document||{},gradingSection=grading.section||{},gradingApplication=grading.application||{};id("grading-section").textContent=gradingSection.number?`${gradingSection.number} ${gradingSection.title||""}`:"No grading reference declared";const gradingValues=id("grading-values"),gradePair=(k,v)=>gradingValues.append(make("dt","",k),make("dd","",v||"—"));gradePair("Document",gradingDocument.file_name);gradePair("Title",gradingDocument.title);gradePair("Version / date",[gradingDocument.version,gradingDocument.date].filter(Boolean).join(" / "));gradePair("SHA-256",gradingDocument.sha256);gradePair("Subsections",(gradingSection.grading_subsections||[]).map(x=>`${x.number} ${x.title} (PDF ${x.pdf_pages})`).join("; "));(grading.levels||[]).forEach(level=>{const card=make("article","tool-card");card.append(make("h3",`review-${level.id}`,level.label||level.id),make("p","",level.description));id("grading-levels").append(card)});if(!(grading.levels||[]).length)id("grading-levels").append(make("p","empty","This legacy review does not declare a grading reference."));id("grading-note").textContent=gradingApplication.note||"Review levels are not available for this legacy report; normalized severity remains visible.";
const rawReviewLevels=["error","warning","style","information","unmapped"],fallbackLevelCounts=rawReviewLevels.reduce((out,level)=>{out[level]=(review.findings||[]).filter(x=>(x.review_level||"unmapped")===level).length;return out},{}),levelCounts=review.review_level_counts||fallbackLevelCounts,unmappedCount=Number(levelCounts.unmapped||0),counts=review.finding_counts||{},cards=[["Source files",review.source_manifest?.total_files],["All findings",review.total_findings],["Build-aware",counts["build-aware"]||0],["Source-only",counts["source-only"]??review.total_findings],["Reference-mapped",Math.max(0,Number(review.total_findings||0)-unmappedCount)],["Unmapped",unmappedCount],["Diagnostics",review.total_diagnostics],["Valid reports",Object.values(manifest.tools||{}).reduce((n,x)=>n+Number(x.valid_reports||0),0)]];cards.forEach(([label,value])=>{const c=make("article","card");c.append(make("span","muted",label),make("strong","",number(value)));id("cards").append(c)});const omitted=review.report_integrity?.omitted_units||[],gaps=review.coverage_gaps||[];if(omitted.length||gaps.length){const warning=make("p","notice",`${omitted.length} report unit(s) were omitted for integrity reasons; ${gaps.reduce((n,x)=>n+Number(x.excluded||0)+Number(x.unanalyzed||0),0)} file(s) are excluded or unanalyzed.`);id("integrity-warning").append(warning)}
const bars=(target,entries,tone=false)=>{const root=id(target),valid=entries.filter(x=>Number(x[1])>0),max=Math.max(1,...valid.map(x=>Number(x[1])));if(!valid.length){root.append(make("p","empty","No data available."));return}valid.forEach(([label,count])=>{const row=make("div","bar"),track=make("span","track"),fill=make("span","fill");fill.style.width=`${Math.max(1,Number(count)/max*100)}%`;if(tone)fill.style.background=`var(--${rawReviewLevels.includes(label)?label:"unmapped"})`;track.append(fill);row.append(make("span","",label||"<unknown>"),track,make("span","",number(count)));root.append(row)})};const byContext=review.review_level_counts_by_context||{"build-aware":{},"source-only":levelCounts};bars("severity-build",rawReviewLevels.map(x=>[x,byContext["build-aware"]?.[x]||0]),true);bars("severity-source",rawReviewLevels.map(x=>[x,byContext["source-only"]?.[x]||0]),true);bars("cwe-chart",(review.top_cwes||[]).map(x=>[x.cwe,x.count]));bars("file-chart",(review.top_files||[]).map(x=>[x.file,x.count]));bars("tool-build",Object.entries(review.tools||{}).map(([k,v])=>[k,v.finding_counts?.["build-aware"]||0]));bars("tool-source",Object.entries(review.tools||{}).map(([k,v])=>[k,v.finding_counts?.["source-only"]??(v.total_findings||0)]));
Object.entries(review.tools||{}).forEach(([tool,data])=>{const card=make("article","tool-card"),head=make("div");head.append(make("h3","",tool),make("span","badge",data.status||"unknown"));card.append(head);const dl=make("dl","tool-values"),pair=(k,v)=>dl.append(make("dt","",k),make("dd","",v===undefined||v===null?"—":v)),coverage=data.coverage||{};pair("Build-aware findings",number(data.finding_counts?.["build-aware"]));pair("Source-only findings",number(data.finding_counts?.["source-only"]??data.total_findings));pair("Diagnostics",number(data.total_diagnostics));pair("Version",data.version);pair("Effective coverage",`${coverage.analyzed??coverage.covered??0}/${coverage.effective_total??coverage.total??0}`);pair("Attempted",coverage.attempted??coverage.covered??0);pair("Excluded",coverage.excluded||0);pair("Valid reports",data.valid_reports);pair("Units",data.unit_counts?.planned||0);card.append(dl);if(data.reason)card.append(make("p","",data.reason));(data.units||[]).filter(unit=>unit.status!=="completed").forEach(unit=>card.append(make("p","notice",`${unit.id}: ${unit.status}${unit.reason?` — ${unit.reason}`:""}`)));const links=make("div","links");(data.units||[]).forEach(unit=>(unit.artifacts||[]).forEach(a=>links.append(link(a.path,a.path))));if(!links.childNodes.length)links.append(make("span","muted","No native artifacts"));card.append(links);id("tool-cards").append(card)});
const sm=review.source_manifest||{},scope=id("scope-values"),pair=(k,v)=>scope.append(make("dt","",k),make("dd","",v));pair("Inventory files",number(sm.total_files));pair("Compile DB entries",number(manifest.compile_database?.filtered_entries));pair("Analysis context",manifest.analysis_context||"—");pair("Source stable",manifest.source_inventory?.stable===true?"yes":manifest.source_inventory?.stable===false?"no":"—");id("source-summary").textContent=`Source files (${number((sm.files||[]).length)})`;(sm.files||[]).forEach(x=>id("source-files").append(make("li","",x)));
const tableEmpty=(body,columns,text)=>{const tr=make("tr"),td=make("td","empty",text);td.colSpan=columns;tr.append(td);body.append(tr)};id("overlap-count").textContent=`${number(review.overlap_groups?.length)} groups`;const overlapBody=id("overlap-body"),state={page:1,fingerprints:null};(review.overlap_groups||[]).forEach(g=>{const tr=make("tr"),action=make("td"),button=make("button","","View findings");button.onclick=()=>{state.fingerprints=new Set(g.fingerprints||[]);state.page=1;renderFindings();window.location.hash="findings"};action.append(button);tr.append(make("td","",g.category),make("td","location",`${g.canonical_path}:${g.line}`),make("td","",(g.tools||[]).join(", ")),make("td","",number(g.fingerprints?.length)),action);overlapBody.append(tr)});if(!overlapBody.childNodes.length)tableEmpty(overlapBody,5,"No cross-tool overlap groups.");
id("diagnostic-count").textContent=`${number(review.diagnostics?.length)} diagnostics`;const db=id("diagnostic-body");(review.diagnostics||[]).forEach(x=>{const tr=make("tr");const evidence=make("td");evidence.append(link("native",x.source_artifact));tr.append(make("td","",x.severity),make("td","",x.tool),make("td","",x.category),make("td","",x.fatal?"yes":"no"),make("td","location",location(x)),make("td","",x.message),evidence);db.append(tr)});if(!db.childNodes.length)tableEmpty(db,7,"No tool diagnostics.");
const findings=(review.findings||[]).map(x=>({...x,evidence_context:x.evidence_context||"source-only",review_level:x.review_level||"unmapped"})),options=(select,values)=>[...new Set(values.filter(Boolean))].sort().forEach(x=>{const o=make("option","",x);o.value=x;select.append(o)});options(id("review-level"),findings.map(x=>x.review_level));options(id("severity"),findings.map(x=>x.severity));options(id("tool"),findings.map(x=>x.tool));options(id("cwe"),findings.map(x=>x.cwe));id("finding-total").textContent=`${number(findings.length)} findings`;const buildCount=findings.filter(x=>x.evidence_context==="build-aware").length,sourceCount=findings.filter(x=>x.evidence_context==="source-only").length;if(buildCount){id("context").value="build-aware";if(sourceCount){const notice=id("context-notice");notice.hidden=false;notice.textContent=`Showing build-aware evidence by default. ${number(sourceCount)} source-only finding(s) remain available in the Context filter.`}}
function renderFindings(){const q=id("search").value.toLowerCase(),context=id("context").value,reviewLevel=id("review-level").value,sev=id("severity").value,tool=id("tool").value,cwe=id("cwe").value,sort=id("sort").value;let rows=findings.filter(x=>(!state.fingerprints||state.fingerprints.has(x.fingerprint))&&(!context||x.evidence_context===context)&&(!reviewLevel||x.review_level===reviewLevel)&&(!sev||x.severity===sev)&&(!tool||x.tool===tool)&&(!cwe||x.cwe===cwe)&&(!q||[x.rule_id,x.cwe,x.canonical_path,x.message].some(v=>String(v||"").toLowerCase().includes(q))));rows=[...rows].sort((a,b)=>sort==="location"?location(a).localeCompare(location(b)):sort==="tool"?a.tool.localeCompare(b.tool):sort==="rule"?a.rule_id.localeCompare(b.rule_id):(b.rank-a.rank));const size=Number(id("page-size").value),pages=Math.max(1,Math.ceil(rows.length/size));state.page=Math.min(state.page,pages);const body=id("finding-body");body.replaceChildren();rows.slice((state.page-1)*size,state.page*size).forEach(x=>{const tr=make("tr"),e=make("td");e.append(link("native",x.source_artifact));tr.append(make("td",`review-${x.review_level}`,x.review_level),make("td",`severity-${x.severity}`,x.severity),make("td","",x.evidence_context),make("td","",x.tool),make("td","",x.rule_id),make("td","",x.cwe||"—"),make("td","location",location(x)),make("td","",x.message),e);body.append(tr)});if(!body.childNodes.length)tableEmpty(body,9,"No findings match the filters.");id("page-status").textContent=`${number(rows.length)} results · page ${state.page}/${pages}`;id("previous").disabled=state.page<=1;id("next").disabled=state.page>=pages}
["search","context","review-level","severity","tool","cwe","sort","page-size"].forEach(x=>id(x).addEventListener("input",()=>{state.page=1;renderFindings()}));id("previous").onclick=()=>{state.page--;renderFindings()};id("next").onclick=()=>{state.page++;renderFindings()};id("reset").onclick=()=>{["search","context","review-level","severity","tool","cwe"].forEach(x=>id(x).value="");id("sort").value="priority";state.page=1;state.fingerprints=null;renderFindings()};renderFindings();window.__codeAnalyzerDashboard.ready()})();
</script></body></html>'''
